datasets:
  aic_instruct_tuning:
    data_type: images
    vis_processor:
      train:
        name: "blip2_image_multitask_train"
        image_size: 448
    text_processor:
      train:
        name: "blip2_densecap_train"
    build_info:
      image_path: /data/datasets/dataset_pose/aic
      ann_path: 
        train: /data/datasets/dataset_pose/aic/aic_annotations/aic_instruction_tuning.jsonl
      template_path: