datasets:
  ccslaion_instruct_tuning:
    data_type: images
    vis_processor:
      train:
        name: "blip2_image_multitask_train"
        image_size: 448
    text_processor:
      train:
        name: "blip2_densecap_train"
    build_info:
      image_path: /data/datasets/ccs_laion/sampled_1M_images/images_4000_2
      ann_path: 
        train: /data/datasets/ccs_laion/sampled_1M_images/ccslaion_instruction_tuning.jsonl
      template_path: