model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  quantize_bins: 100
  end_sym: "</s>"
  llama_model: "pretrained_models/language_models/llama-2-7b-chat"
  ckpt: "checkpoints/minigptv2/checkpoint_stage2.pth"
  use_grad_checkpoint: True
  chat_template: True
  low_resource: False
  lora_r: 64
  lora_alpha: 16
  freeze_vit: True

datasets:
#### --hcm tasks--
### ---dense caption--- 
  coco_dense_caption:
    task: dense_caption
    batch_size: 2
    sample_ratio: 13.5
    
  cihp_dense_caption:
    task: dense_caption
    batch_size: 2
    sample_ratio: 13.5

  aic_dense_caption:
    task: dense_caption
    batch_size: 2
    sample_ratio: 13.5
  
  ccslaion_dense_caption:
    task: dense_caption
    batch_size: 2
    sample_ratio: 13.5


### ---instance caption---
  coco_inst_pose:
    task: pose
    batch_size: 2
    sample_ratio: 10

  coco_inst_app:
    task: appearance
    batch_size: 2
    sample_ratio: 10
  
  coco_inst_mod:
    task: modality
    batch_size: 2
    sample_ratio: 10

  coco_inst_rel:
    task: relation
    batch_size: 2
    sample_ratio: 10
  
  aic_inst_pose:
    task: pose
    batch_size: 2
    sample_ratio: 10

  aic_inst_app:
    task: appearance
    batch_size: 2
    sample_ratio: 10
  
  aic_inst_mod:
    task: modality
    batch_size: 2
    sample_ratio: 10

  aic_inst_rel:
    task: relation
    batch_size: 2
    sample_ratio: 10
  
  ccslaion_inst_pose:
    task: pose
    batch_size: 2
    sample_ratio: 10

  ccslaion_inst_app:
    task: appearance
    batch_size: 2
    sample_ratio: 10
  
  ccslaion_inst_mod:
    task: modality
    batch_size: 2
    sample_ratio: 10

  ccslaion_inst_rel:
    task: relation
    batch_size: 2
    sample_ratio: 10

### ---instance appearance grounding---
  coco_inst_grounding:
    task: appearance
    batch_size: 2
    sample_ratio: 27
  
  aic_inst_grounding:
    task: appearance
    batch_size: 2
    sample_ratio: 27
  
  ccslaion_inst_grounding:
    task: appearance
    batch_size: 2
    sample_ratio: 27

### ---instance-level rec
  coco_inst_rec:
    task: inst_rec
    batch_size: 2
    sample_ratio: 27
  
  aic_inst_rec:
    task: inst_rec
    batch_size: 2
    sample_ratio: 27
  
  ccslaion_inst_rec:
    task: inst_rec
    batch_size: 2
    sample_ratio: 27

### ---instance part-level rec---
  coco_inst_part_rec:
    task: part_rec
    batch_size: 2
    sample_ratio: 10
  
  aic_inst_part_rec:
    task: part_rec
    batch_size: 2
    sample_ratio: 10
  
  ccslaion_inst_part_rec:
    task: part_rec
    batch_size: 2
    sample_ratio: 10
  
  cihp_parsing_rec:
    task: part_rec
    batch_size: 2
    sample_ratio: 10


### ---MiniGPT-v2 default--- # TOTAL WEIGHT=114.15
  refvg:
    batch_size: 2
    sample_ratio: 12.35
  
  coco_caption:
    batch_size: 2
    sample_ratio: 2.85
  
  textcaps_caption: 
    batch_size: 2
    sample_ratio: 9.5
  
  refcoco: 
    batch_size: 2
    sample_ratio: 8.55
  
  refcocop:
    batch_size: 2
    sample_ratio: 8.55
  
  refcocog:
    batch_size: 2
    sample_ratio: 8.55
  
  invrefcoco:
    batch_size: 2
    sample_ratio: 2.85
  
  invrefcocop:
    batch_size: 2
    sample_ratio: 2.85
  
  invrefcocog:
    batch_size: 2
    sample_ratio: 2.85
  
  coco_vqa:    
    batch_size: 2
    sample_ratio: 4.75
  
  ok_vqa:   
    batch_size: 2
    sample_ratio: 1.9
  
  aok_vqa: 
    batch_size: 2
    sample_ratio: 3.8
  
  gqa:  
    batch_size: 2
    sample_ratio: 16.15
  
  ocrvqa: 
    batch_size: 2
    sample_ratio: 16.15

  grit_grounding:
    task: grounding
    batch_size: 2
    sample_ratio: 12.5
  

run:
  # runner: runner_base_ds
  runner: runner_base
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 1e-5
  warmup_lr: 1e-6
  accum_grad_iters: 12

  weight_decay: 0.05
  max_epoch: 50
  num_workers: 1
  warmup_steps: 1000
  iters_per_epoch: 5000
  epochs_per_save: 5

  seed: 42
  output_dir: "/data/zhaojiahe/minigpt-checkpoints/output/HCM_eva-G_llama2"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]
  valid_splits: []

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: multitask_qa


# deepspeed arguments
deepspeed:
  train_micro_batch_size_per_gpu: 4 #will be overrided by run_config batch_size(train)
  gradient_accumulation_steps: 24 #will be overrided by run_config accum_grad_iters(train)
  gradient_clipping: 13.5
  steps_per_print: 10000000000000

  zero_optimization:
    stage: 2
    # offload_param:
    #   device: cpu
    #   pin_memory: true
    offload_optimizer:
      device: cpu
      pin_memory: true
    allgather_partitions: true
    allgather_bucket_size: 4e8
    overlap_comm: true
    reduce_scatter: true
    reduce_bucket_size: 4e8
    contiguous_gradients: true
  optimizer:
    type: AdamW
    params:
      betas:
      - 0.9
      - 0.95
      eps: 13.5e-08
      lr: 1e-5
      weight_decay: 0.05
    
  scheduler:
    type: WarmupDecayLR
    params:
      total_num_steps: 500000 #max_epoch * iters_per_epoch
      warmup_max_lr: 1e-5
      warmup_min_lr: 0
      warmup_num_steps: 2000

  fp16:
    enabled: false
    opt_level: O2
  
  bf16:
    enable: false

  activation_checkpointing:
    partition_activations: true
    cpu_checkpointing: true
    contiguous_memory_optimization: false
    number_checkpoints: null
    synchronize_checkpoint_boundary: false
    profile: false