model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  quantize_bins: 100
  end_sym: "</s>"
  llama_model: "pretrained_models/language_models/llama-2-7b-chat"
  ckpt: "checkpoints/minigptv2/checkpoint_stage2.pth"
  use_grad_checkpoint: True
  chat_template: True
  low_resource: False
  lora_r: 64
  lora_alpha: 16

datasets:
### ---MiniGPT-v2 default---
  refvg:
    batch_size: 2
    sample_ratio: 20
  
  coco_caption:
    batch_size: 2
    sample_ratio: 10
  
  textcaps_caption: 
    batch_size: 2
    sample_ratio: 30
  
  refcoco: 
    batch_size: 2
    sample_ratio: 25
  
  refcocop:
    batch_size: 2
    sample_ratio: 25
  
  refcocog:
    batch_size: 2
    sample_ratio: 25
  
  invrefcoco:
    batch_size: 2
    sample_ratio: 10
  
  invrefcocop:
    batch_size: 2
    sample_ratio: 10
  
  invrefcocog:
    batch_size: 2
    sample_ratio: 10
  
  coco_vqa:    
    batch_size: 2
    sample_ratio: 15
  
  ok_vqa:   
    batch_size: 2
    sample_ratio: 8
  
  aok_vqa: 
    batch_size: 2
    sample_ratio: 12
  
  gqa:  
    batch_size: 2
    sample_ratio: 50
  
  ocrvqa: 
    batch_size: 2
    sample_ratio: 30

### ---Reference Segmentation---
  refcoco_seg:
    batch_size: 1
    sample_ratio: 100
  
  refcocop_seg:
    batch_size: 1
    sample_ratio: 100
  
  refcocog_seg:
    batch_size: 1
    sample_ratio: 100
  
  invrefcoco_seg:
    batch_size: 1
    sample_ratio: 100
  
  invrefcocop_seg:
    batch_size: 1
    sample_ratio: 100
  
  invrefcocog_seg:
    batch_size: 1
    sample_ratio: 100

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 5e-6
  warmup_lr: 1e-6
  accum_grad_iters: 24

  weight_decay: 0.05
  max_epoch: 60
  num_workers: 6
  warmup_steps: 1000
  iters_per_epoch: 10000
  epochs_per_save: 10

  seed: 42
  output_dir: "output/Refseg_eva-G_llama2"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]
  valid_splits: []

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: refseg