model:
  arch: minigpt_v2_pose
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  quantize_bins: 100
  end_sym: "</s>"
  llama_model: "pretrained_models/language_models/llama-2-7b-chat"
  ckpt: "checkpoints/minigptv2/checkpoint_stage2.pth"
  use_grad_checkpoint: False
  chat_template: True
  low_resource: False
  lora_r: 64
  lora_alpha: 16
  freeze_vit: False
  half_freeze: False
  tune_posembed: False
  tune_layernorm: False
  use_vit_adapter: True

  num_keypoints: 19
  point_loss_alpha: 10.0

datasets:
### ---detection---
  coco_det_qa:
    task: detection
    batch_size: 1
    sample_ratio: 6.4
    text_processor:
      train:
        max_bbox_num: 20

  crowdhuman_det_qa:
    task: detection
    batch_size: 1
    sample_ratio: 1.5
    text_processor:
      train:
        max_bbox_num: 20

  cityperson_det_qa:
    task: detection
    batch_size: 1
    sample_ratio: 2.5
    text_processor:
      train:
        max_bbox_num: 20
    
  ECP_det_qa:
    task: detection
    batch_size: 1
    sample_ratio: 7.5
    text_processor:
      train:
        max_bbox_num: 20

  WiderPerson_det_qa:
    task: detection
    batch_size: 1
    sample_ratio: 8
    text_processor:
      train:
        max_bbox_num: 20

  widerpedestrian_det_qa:
    task: detection
    batch_size: 1
    sample_ratio: 2.5
    text_processor:
      train:
        max_bbox_num: 20

### ---pose---
  aic_pose_qa:
    task: pose_estimation
    batch_size: 1
    sample_ratio: 37.8
    text_processor:
      train:
        name: blip2_text_pose_reg_train
      eval:
        name: blip2_text_pose_reg_eval
    build_info:
      template_path: minigpt4/configs/datasets/multitask_qa/pose_estimation/qa_reg_template.json

  coco_pose_qa:
    task: pose_estimation
    batch_size: 1
    sample_ratio: 15.0
    text_processor:
      train:
        name: blip2_text_pose_reg_train
      eval:
        name: blip2_text_pose_reg_eval
    build_info:
      template_path: minigpt4/configs/datasets/multitask_qa/pose_estimation/qa_reg_template.json

  PoseTrack_pose_qa:
    task: pose_estimation
    batch_size: 1
    sample_ratio: 9.9
    text_processor:
      train:
        name: blip2_text_pose_reg_train
      eval:
        name: blip2_text_pose_reg_eval
    build_info:
      template_path: minigpt4/configs/datasets/multitask_qa/pose_estimation/qa_reg_template.json

  # # NOT USED FOR TRAINING. dataset need to be checked. 
  # MHP_pose_qa:
  #   task: pose_estimation
  #   batch_size: 1
  #   sample_ratio: 2
  #   # build_info:
  #   #   ann_path:
  #   #     val: /data/datasets/dataset_pose/MHP/MHP_pose_val_bbox.jsonl

  3DPW_pose_qa:
    task: pose_estimation
    batch_size: 1
    sample_ratio: 1.7
    text_processor:
      train:
        name: blip2_text_pose_reg_train
      eval:
        name: blip2_text_pose_reg_eval
    build_info:
      template_path: minigpt4/configs/datasets/multitask_qa/pose_estimation/qa_reg_template.json

  halpe_pose_qa:
    task: pose_estimation
    batch_size: 1
    sample_ratio: 4.1
    text_processor:
      train:
        name: blip2_text_pose_reg_train
      eval:
        name: blip2_text_pose_reg_eval
    build_info:
      template_path: minigpt4/configs/datasets/multitask_qa/pose_estimation/qa_reg_template.json

  penn_action_pose_qa:
    task: pose_estimation
    batch_size: 1
    sample_ratio: 16.4
    text_processor:
      train:
        name: blip2_text_pose_reg_train
      eval:
        name: blip2_text_pose_reg_eval
    build_info:
      template_path: minigpt4/configs/datasets/multitask_qa/pose_estimation/qa_reg_template.json

  JRDB_pose_qa:
    task: pose_estimation
    batch_size: 1
    sample_ratio: 31
    text_processor:
      train:
        name: blip2_text_pose_reg_train
      eval:
        name: blip2_text_pose_reg_eval
    build_info:
      template_path: minigpt4/configs/datasets/multitask_qa/pose_estimation/qa_reg_template.json

  human36m_pose_qa:
    task: pose_estimation
    batch_size: 1
    sample_ratio: 31
    text_processor:
      train:
        name: blip2_text_pose_reg_train
      eval:
        name: blip2_text_pose_reg_eval
    build_info:
      template_path: minigpt4/configs/datasets/multitask_qa/pose_estimation/qa_reg_template.json

### ---parsing---
  cihp_parsing_qa:
    task: parsing
    batch_size: 1
    sample_ratio: 13.9
    vis_processor:
      train:
        data_cfg:
          is_flip: False
    text_processor:
      train:
        sample_p: 0.1
        max_polygon_len: 40
    build_info:
      ann_path:
        train: /data/datasets/dataset_parsing/CIHP/instance-level_human_parsing/CIHP_train_polygon_bbox.jsonl
      template_path: minigpt4/configs/datasets/multitask_qa/parsing/qa_template_bbox.json

  lip_parsing_qa:
    task: parsing
    batch_size: 1
    sample_ratio: 4.5
    vis_processor:
      train:
        data_cfg:
          is_flip: False
    text_processor:
      train:
        sample_p: 0.1
        max_polygon_len: 40
    build_info:
      ann_path:
        train: /data/datasets/dataset_parsing/LIP/TrainVal_parsing_annotations/LIP_train_polygon_bbox.jsonl
      template_path: minigpt4/configs/datasets/multitask_qa/parsing/qa_template_bbox.json
  
  vip_parsing_qa:
    task: parsing
    batch_size: 1
    sample_ratio: 8.1
    vis_processor:
      train:
        data_cfg:
          is_flip: False
    text_processor:
      train:
        sample_p: 0.1
        max_polygon_len: 40
    build_info:
      ann_path:
        train: /data/datasets/dataset_parsing/VIP_new/VIP_Fine/annotations/VIP_train_polygon_bbox.jsonl
      template_path: minigpt4/configs/datasets/multitask_qa/parsing/qa_template_bbox.json
  
  deepfashion2_parsing_qa:
    task: parsing
    batch_size: 1
    sample_ratio: 9.6
    vis_processor:
      train:
        data_cfg:
          is_flip: False
    text_processor:
      train:
        sample_p: 0.1
        max_polygon_len: 40
    build_info:
      ann_path:
        train: /data/datasets/dataset_parsing/DeepFashion2/deepfashion2_train_polygon_bbox.jsonl
      template_path: minigpt4/configs/datasets/multitask_qa/parsing/qa_template_bbox.json
  
  # # NOT USED FOR TRAINING. dataset need to be checked. 
  # modanet_parsing_qa: 
  #   task: parsing
  #   batch_size: 1
  #   # modanet validation set has no annotations

### ---MiniGPT-v2 default---
  refvg:
    batch_size: 1
    sample_ratio: 12.35
  
  coco_caption:
    batch_size: 1
    sample_ratio: 2.85
  
  textcaps_caption: 
    batch_size: 1
    sample_ratio: 9.5
  
  refcoco: 
    batch_size: 1
    sample_ratio: 8.55
  
  refcocop:
    batch_size: 1
    sample_ratio: 8.55
  
  refcocog:
    batch_size: 1
    sample_ratio: 8.55
  
  invrefcoco:
    batch_size: 1
    sample_ratio: 2.85
  
  invrefcocop:
    batch_size: 1
    sample_ratio: 2.85
  
  invrefcocog:
    batch_size: 1
    sample_ratio: 2.85
  
  coco_vqa:    
    batch_size: 1
    sample_ratio: 4.75
  
  ok_vqa:   
    batch_size: 1
    sample_ratio: 1.9
  
  aok_vqa: 
    batch_size: 1
    sample_ratio: 3.8
  
  gqa:  
    batch_size: 1
    sample_ratio: 16.15
  
  ocrvqa: 
    batch_size: 1
    sample_ratio: 16.15
  

run:
  # runner: runner_base_ds
  runner: runner_base
  task: image_text_pretrain_pointreg
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 8e-5
  warmup_lr: 1e-6
  accum_grad_iters: 24

  weight_decay: 0.05
  max_epoch: 200
  num_workers: 1
  warmup_steps: 1000
  iters_per_epoch: 5000
  epochs_per_save: 10

  seed: 42
  output_dir: "output/Multitask_eva-G_llama2"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]
  valid_splits: []

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: multitask_qa


# deepspeed arguments
deepspeed:
  train_micro_batch_size_per_gpu: 4 #will be overrided by run_config batch_size(train)
  gradient_accumulation_steps: 24 #will be overrided by run_config accum_grad_iters(train)
  gradient_clipping: 1.0
  steps_per_print: 10000000000000

  zero_optimization:
    stage: 2
    # offload_param:
    #   device: cpu
    #   pin_memory: true
    offload_optimizer:
      device: cpu
      pin_memory: true
    allgather_partitions: true
    allgather_bucket_size: 4e8
    overlap_comm: true
    reduce_scatter: true
    reduce_bucket_size: 4e8
    contiguous_gradients: true
  optimizer:
    type: AdamW
    params:
      betas:
      - 0.9
      - 0.95
      eps: 1.0e-08
      lr: 1e-5
      weight_decay: 0.05
    
  scheduler:
    type: WarmupDecayLR
    params:
      total_num_steps: 500000 #max_epoch * iters_per_epoch
      warmup_max_lr: 1e-5
      warmup_min_lr: 0
      warmup_num_steps: 2000

  fp16:
    enabled: false
    opt_level: O2
  
  bf16:
    enable: false

  activation_checkpointing:
    partition_activations: true
    cpu_checkpointing: true
    contiguous_memory_optimization: false
    number_checkpoints: null
    synchronize_checkpoint_boundary: false
    profile: false