datasets:
  ccslaion_inst_part_rec:
    data_type: images
    vis_processor:
      train:
        name: "blip2_image_multitask_train"
        image_size: 448
    text_processor:
      train:
        name: "blip2_text_instpartrec_train"
        bbox_ref_prob: 0.2
    build_info:
      image_path: /data/datasets/ccs_laion/sampled_1M_images/images_4000
      ann_path: 
        train: /data/datasets/ccs_laion/sampled_1M_images/ccslaion_instance_annotation_ref_train.jsonl
      template_path: minigpt4/configs/datasets/instance_tasks/rec/part_rec_template.json
