datasets:
  ccslaion_inst_pose:
    data_type: images
    vis_processor:
      train:
        name: "blip2_image_multitask_train"
        image_size: 448
      eval:
        name: "blip2_image_multitask_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip2_text_instcap_train"
        bbox_ref_prob: 0.2
      eval:
        name: "blip2_text_instcap_eval"
        bbox_ref_prob: 0.2
    build_info:
      image_path: /data/datasets/ccs_laion/sampled_1M_images/images_4000
      ann_path: 
        train: /data/datasets/ccs_laion/sampled_1M_images/ccslaion_instance_annotation_ref_train.jsonl
      template_path: minigpt4/configs/datasets/instance_tasks/pose/pose_template.json
