model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  quantize_bins: 100
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "pretrained_models/language_models/llama-2-7b-chat"
  ckpt: "checkpoints/minigptv2/checkpoint_stage3.pth"
  lora_r: 64
  lora_alpha: 16
  freeze_vit: True


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  refaic:
    eval_file_path: inference_cases/rec/rec_aic_wotaskid.jsonl        
    max_new_tokens: 500
    batch_size: 4
  
  ref:
    eval_file_path: inference_cases/knowledge_reference/reg_attr.jsonl
    max_new_tokens: 500
    batch_size: 4
  
  coco:
    eval_file_path: inference_cases/hint_detection.jsonl
    max_new_tokens: 100
    batch_size: 1
  
  vqa:
    eval_file_path: inference_cases/benchmark_tasks/benchmark_tasks.jsonl
    max_new_tokens: 500
    batch_size: 4
  
  hcm_qa:
    eval_file_path: /home/human/data/humanLLM_test_benchmark/questions/multiperson_relation_multichoice.jsonl
    max_new_tokens: 500
    batch_size: 4

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: output/HCM_free_eval/ablations/prompting
  dataset_type: multichoice
  # dataset_type: bbox
  # dataset_type: multi_bbox
  # dataset_type: vizwiz
  

  

