datasets:
  textcaps_caption:
    data_type: images
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    build_info:
      image_path: /data/datasets/dataset_ref/text_caption/train_images 
      ann_path: minigptv2_json/TextCaps_0.1_train.json


